# This file was generated by GoReleaser. DO NOT EDIT.
cask "fuse" do
  version "0.19.0"

  on_macos do
    on_intel do
      sha256 "d2efac073752c77d2a2120ed891ea73a2e61636afa7f4c674bc936fc7d79208a"
      url "https://github.com/folsomintel/fuse/releases/download/v#{version}/fuse-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5b0202f7b59bb63a271d94fd8c26c3dd43f650757866d0d51e84960f7f2d1d1a"
      url "https://github.com/folsomintel/fuse/releases/download/v#{version}/fuse-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cae2c8646011d8428b882229ec7f21e7d62f628c854ce1ae1bcc001bf0107219"
      url "https://github.com/folsomintel/fuse/releases/download/v#{version}/fuse-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "473c01ceb2d682e6be68251ce8e730212902e2b49d12f090dec8ece372cb787a"
      url "https://github.com/folsomintel/fuse/releases/download/v#{version}/fuse-cli_Linux_arm64.tar.gz"
    end
  end

  name "fuse"
  desc "Operator CLI for the Fuse microVM control plane"
  homepage "https://github.com/folsomintel/fuse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fuse"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fuse"]
    end
  end

  # No zap stanza required

end
