# This file was generated by GoReleaser. DO NOT EDIT.
cask "fuse" do
  version "0.9.2"

  on_macos do
    on_intel do
      sha256 "3348ab1f823c952659c01690179227d2b2db34e3f81eb17c04636940628d14b9"
      url "https://github.com/folsomintel/fuse/releases/download/v#{version}/fuse-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9584bdc78afa6db23b265c481bd8157ce2e587bd38e732f64347c2c451ca86f4"
      url "https://github.com/folsomintel/fuse/releases/download/v#{version}/fuse-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d615ff9da5780166795b162b787cfdd08332124c66251c54fe77a403531133f0"
      url "https://github.com/folsomintel/fuse/releases/download/v#{version}/fuse-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "beaffe45d5a2c14ea498917c53a56d300dc6e163c1a4f6716efc76edab3453ef"
      url "https://github.com/folsomintel/fuse/releases/download/v#{version}/fuse-cli_Linux_arm64.tar.gz"
    end
  end

  name "fuse"
  desc "Operator CLI for the Fuse microVM control plane"
  homepage "https://github.com/folsomintel/fuse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fuse"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fuse"]
    end
  end

  # No zap stanza required

end
