# This file was generated by GoReleaser. DO NOT EDIT.
cask "fuse" do
  version "0.30.0"

  on_macos do
    on_arm do
      sha256 "b7c8568ca127978f79b75020c65c35d66150030195ffca2a008ef2336cceb0e6"
      url "https://github.com/folsomintel/fuse/releases/download/v#{version}/fuse-cli_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2f00d3c04a6b8039a0d5a0f88ee6aea1419c240ff002199e2447430ddb4a8e26"
      url "https://github.com/folsomintel/fuse/releases/download/v#{version}/fuse-cli_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4659d2d14b85275edee823af4b02078323882bac2ef309ccff871d10a1026716"
      url "https://github.com/folsomintel/fuse/releases/download/v#{version}/fuse-cli_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "25bc42cd4c7609386aeb100d62456614958cd1ecbf73b0a4b1e980b086b427c0"
      url "https://github.com/folsomintel/fuse/releases/download/v#{version}/fuse-cli_Linux_x86_64.tar.gz"
    end
  end

  name "fuse"
  desc "Operator CLI for the Fuse microVM control plane"
  homepage "https://github.com/folsomintel/fuse"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fuse"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fuse"]
    end
  end

  # No zap stanza required
end
